/// <reference path="./node_modules/tns-core-modules/tns-core-modules.d.ts" /> Needed for autocompletion and compilation.
/// <reference path="./typings/lodash.d.ts" />
/// <reference path="./node_modules/nativescript-geolocation/nativescript-geolocation.d.ts" />
/// <reference path="./node_modules/nativescript-geolocation/nativescript-geolocation.d.ts" />
/// <reference path="./node_modules/nativescript-geolocation/index.d.ts" />
/// <reference path="./node_modules/nativescript-geolocation/location-monitor.d.ts" />
/// <reference path="./node_modules/nativescript-geolocation/location.d.ts" />
/// <reference path="./node_modules/nativescript-plugin-firebase/firebase-common.d.ts" />
/// <reference path="./node_modules/nativescript-plugin-firebase/firebase.d.ts" />
