import {CriteriaItem} from "./criteriaItem";

export interface WineTasting {
    id?: string;
    estate?: string;
    region?: CriteriaItem;
    name?: string;
    country?: CriteriaItem;
    aoc?: CriteriaItem;
    year?: number;
    wineType?: CriteriaItem;
    alcohol?: number;
    isBiodynamic?: boolean;
    isBlindTasting?: boolean;
    grapes?: CriteriaItem[];
    wineTabNotes?: string;
    tastingDate?: number;
    synthesisTabNotes?: string;
    color?: string;
    finalRating?: number;
    sightTabNotes?: string;
    smellTabNotes?: string;
    tasteTabNotes?: string;
    aromas?: CriteriaItem[];
    defects?: CriteriaItem[];
    flavors?: CriteriaItem[];
    flavorDefects?: CriteriaItem[];
    attacks?: CriteriaItem[];
    limpidities?: CriteriaItem[];
    shines?: CriteriaItem[];
    tears?: CriteriaItem[];
    hasBubbles?: boolean;
    hasDeposit?:boolean;
    intensities?: CriteriaItem[];
    balances?: CriteriaItem[];
    length?: CriteriaItem[];
    meatsNotes?: string;
    containsPicture?: boolean;
    winePairing?: string;
}
