/// <reference path="../node_modules/tns-core-modules/tns-core-modules.d.ts" /> Enable smart suggestions and completions in Visual Studio Code JavaScript projects.
/// <reference path="./definitions/lodash.d.ts" />
/// <reference path="../app/definitions/lodash.d.ts" />
/// <reference path="../node_modules/nativescript-geolocation/nativescript-geolocation.d.ts" />
/// <reference path="../node_modules/nativescript-geolocation/nativescript-geolocation.d.ts" />
/// <reference path="../node_modules/nativescript-geolocation/index.d.ts" />
/// <reference path="../node_modules/nativescript-geolocation/location-monitor.d.ts" />
/// <reference path="../node_modules/nativescript-geolocation/location.d.ts" />
/// <reference path="../node_modules/nativescript-plugin-firebase/firebase-common.d.ts" />
/// <reference path="../node_modules/nativescript-plugin-firebase/firebase.d.ts" />
